# Generated by Django 4.1.7 on 2023-03-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('activePlayerInGameId', models.IntegerField(null=True)),
                ('boardState', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('inGameId', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blockoo_site.boardstate')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blockoo_site.piece')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blockoo_site.player')),
            ],
        ),
    ]
