# Generated by Django 4.2 on 2023-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockoo_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
