# Generated by Django 4.2 on 2023-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockoo_site', '0002_player_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstate',
            name='gameIsOver',
            field=models.BooleanField(default=False),
        ),
    ]
