# Generated by Django 2.2.7 on 2019-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockoo', '0002_boardmodel_currentplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='currentPlayer',
            field=models.IntegerField(),
        ),
    ]
